name: Generate
"on":
  workflow_dispatch:
    inputs:
      force:
        description: ""
        type: ""
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v7
    with:
      languages: '- typescript: ./'
      mode: pr
      openapi_doc_location: https://api-docs-nine-delta.vercel.app/cloud/openapi.json
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
